import React from 'react';
import Layout from '../components/Layout';

const PrivacyPolicy = () => (
  <Layout showFloatingMenu={false}>
    <div className="py-16 bg-gradient-to-b from-background to-gray-50">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8">
          <h1 className="text-4xl md:text-5xl font-bold text-primary mb-4">Privacy Policy</h1>
          <p className="text-lg text-text-secondary">Your privacy is important to us</p>
        </div>
        <div className="bg-white rounded-2xl shadow-lg p-8 border border-gray-100">
          <div className="text-center mb-6">
            <p className="text-sm text-gray-600">Last updated on 23rd April 2025</p>
            <p className="text-sm text-gray-600 mt-2">Contact: <a href="mailto:support@wotzapmsg.com" className="text-primary underline">support@wotzapmsg.com</a> | <a href="tel:9316360039" className="text-primary underline">9316360039</a></p>
          </div>
          
          <div className="prose prose-lg max-w-none text-text-secondary">
            <p className="mb-6">
              This platform (Hereinafter Referred to as "Platform", "Mobile Application") is a Website & Mobile Based Client Communication integration platform.
            </p>

            <p className="mb-6">
              This Privacy Policy (hereinafter referred to as "Policy"), helps the users accessing the Website/App ("User"/ "You"/ "Your") and the Service therein to understand the type of information collected, the purpose for which the information is collected; how the information is used; the intended recipients of such information; and how the information is protected. We take protection and proper use of Your information seriously and are committed to protecting such information in Our possession. We advise You to read this Policy carefully prior to Your access of Website/App, use of Services, or creation of an Account on the Website/App. If You do not agree to this Policy, please do not access Our Website/App, use Our Services, or create an Account in Our Website/App.
            </p>

            <p className="mb-6">
              This Policy is published and shall be construed to be in accordance with the provisions of the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data of Information) Rules, 2011 and Information Technology (Intermediaries Guidelines And Digital Media Ethics Code) Rules, 2021 under the Information Technology Act, 2000, Digital Personal Data Protection Act, 2023 and other applicable laws that require publishing of the privacy notice for collection, usage, storage, disclosure and transfer of sensitive personal data or information. Any capitalized terms used herein without definition shall have the meanings assigned to them in Our Terms of Use.
            </p>

            <p className="mb-6">
              We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
            </p>

            <p className="mb-8">
              The terms of this policy will be effective upon your acceptance of the same (directly or indirectly in electronic form, by use of the platform and/or by creating a registered account on the platform (hereinafter referred to as "account") and will govern the relationship between you and us for your use of the platform and the services rendered therein.
            </p>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Definitions</h2>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li><strong>Service:</strong> Service means the website and the mobile application operated by our company</li>
              <li><strong>Personal Data:</strong> Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
              <li><strong>Usage Data:</strong> Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Cookies:</strong> Cookies are small files stored on your device (computer or mobile device).</li>
              <li><strong>Data Controller:</strong> Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</li>
              <li><strong>Data Processors (or Service Providers):</strong> Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
              <li><strong>Data Subject (or User):</strong> Data Subject is any living individual who is using our Service and is the subject of Personal Data.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Information Collection and Use</h2>
            <p className="mb-6">
              When You access our Website/App and/or choose to avail the demo of the Product and/or sign up on the Website/App for a free trial of the Product provided by Us through the Website/App, we shall collect certain information from You, the details of which are provided hereinafter. We collect several different types of information for various purposes to provide and improve our Service to you.
            </p>

            <h3 className="text-xl font-semibold text-text-primary mb-3">Types of Data Collected</h3>
            
            <h4 className="text-lg font-semibold text-text-primary mb-2">Personal Data</h4>
            <p className="mb-4">
              While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 mb-6 space-y-1">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number associated with the WhatsApp</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Cookies and Usage Data</li>
              <li>Social Media login credentials</li>
              <li>Any other identifiers and any other sensitive/personal information as defined under the Digital Personal Data Protection Act (DPDPA), 2023.</li>
            </ul>

            <p className="mb-6">
              We may use your Personal Data to contact you with phone calls, newsletters, SMS, marketing or promotional materials and other information that may be of interest to you. And irrespective of the fact that if also you have registered yourself under DND or DNC or NCPR Service, you still authorize us to give you a call for the above mentioned purposes till you have an account with us. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.
            </p>

            <h4 className="text-lg font-semibold text-text-primary mb-2">Usage Data</h4>
            <p className="mb-4">
              We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
            </p>
            <p className="mb-4">
              This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="mb-6">
              When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
            </p>

            <h4 className="text-lg font-semibold text-text-primary mb-2">Behavioral Data</h4>
            <p className="mb-6">
              We shall collect information which is connected with Your activity on the Website/App across all Your devices using Your email or social media log-in details, as well as Services that You search, and opt-ins and communication preferences.
            </p>

            <h4 className="text-lg font-semibold text-text-primary mb-2">Location Data</h4>
            <p className="mb-4">
              We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customise our Service.
            </p>
            <p className="mb-6">
              You can enable or disable location services when you use our Service at any time by way of your device settings.
            </p>

            <h4 className="text-lg font-semibold text-text-primary mb-2">Contact List & Files</h4>
            <p className="mb-6">
              We shall allow you to upload your existing contact list that contains name, mobile number, email and other data fields to initiate conversations from our Website/App. We collect the information related to your device's audio, video and other rich media files such as PDF documents, and enable you to share rich media files to your customers through our Website/App.
            </p>

            <h4 className="text-lg font-semibold text-text-primary mb-2">Tracking & Cookies Data</h4>
            <p className="mb-4">
              We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
            </p>
            <p className="mb-4">
              Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.
            </p>
            <p className="mb-4">
              You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
            </p>
            <p className="mb-2">Examples of Cookies we use:</p>
            <ul className="list-disc pl-6 mb-6 space-y-1">
              <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
              <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
              <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
            </ul>

            <h4 className="text-lg font-semibold text-text-primary mb-2">Device Data</h4>
            <p className="mb-6">
              We collect information about computers, phones, and other connected devices with a web connection and the presence of Our Website/App and Services and integrate this information with the various devices You use. This information includes: device features such as information about operating system, hardware and software versions, battery status, signal availability, available storage space, browser type, app or file names and types, and plug-ins, device activities such as information about the activity and behavior of the device, for example in the background or in front of a window or with mouse movements (which help to distinguish humans from bots), unique identifiers, device ID, games, apps, or accounts You use, Bluetooth signals and information about nearby WiFi access points, beacons and cell towers, Information that We are permitted to collect by turning on access in device configuration, as well as providing access to GPS location, camera or photo, information such as Your mobile operator's name or ISP, language, time zone, mobile phone number, IP address, connection speed, and other devices near Your device or on the network so that We can help You with the streaming of the Services on Your device.
            </p>

            <h4 className="text-lg font-semibold text-text-primary mb-2">Third Party Information</h4>
            <p className="mb-6">
              Information about You that We may receive from third parties services, such as advertising partners, data providers and analytics providers. We may collect Your third-party social media networks information including Your contact lists for these services and information relating to your use of the Website/App in relation to these services, if You choose to link or sign up using a third-party social network or login service (such as Facebook, Twitter, Instagram, or Google). If you link your Account in our Website/App to another service, We may receive information about Your use of that service.
            </p>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Use of Data</h2>
            <p className="mb-4">We use the collected data for various purposes:</p>
            <ul className="list-disc pl-6 mb-6 space-y-1">
              <li>To provide and maintain our Service</li>
              <li>To notify you about changes to our Service</li>
              <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
              <li>To provide customer support</li>
              <li>To gather analysis or valuable information so that we can improve our Service</li>
              <li>To monitor the usage of our Service</li>
              <li>To detect, prevent and address technical issues</li>
              <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
            </ul>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</h2>
            <p className="mb-4">
              If you are from the European Economic Area (EEA), our legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
            </p>
            <p className="mb-4">We may process your Personal Data because:</p>
            <ul className="list-disc pl-6 mb-6 space-y-1">
              <li>We need to perform a contract with you</li>
              <li>You have given us permission to do so</li>
              <li>The processing is in our legitimate interests and it is not overridden by your rights</li>
              <li>For payment processing purposes</li>
              <li>To comply with the law</li>
            </ul>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Retention of Data</h2>
            <p className="mb-6">
              We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.
            </p>
            <p className="mb-6">
              We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.
            </p>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Transfer of Data</h2>
            <p className="mb-4">
              Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
            </p>
            <p className="mb-4">
              If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.
            </p>
            <p className="mb-6">
              Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
            </p>
            <p className="mb-6">
              We will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
            </p>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Disclosure of Data</h2>
            
            <h4 className="text-lg font-semibold text-text-primary mb-2">Business Transaction</h4>
            <p className="mb-6">
              If we are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
            </p>

            <h4 className="text-lg font-semibold text-text-primary mb-2">Disclosure for Law Enforcement</h4>
            <p className="mb-6">
              Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
            </p>

            <h4 className="text-lg font-semibold text-text-primary mb-2">Legal Requirements</h4>
            <p className="mb-4">We may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul className="list-disc pl-6 mb-6 space-y-1">
              <li>To comply with a legal obligation</li>
              <li>To protect and defend the rights or property of our company</li>
              <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>To protect the personal safety of users of the Service or the public</li>
              <li>To protect against legal liability</li>
            </ul>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Security of Data</h2>
            <p className="mb-6">
              The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
            </p>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Your Data Protection Rights under the General Data Protection Regulation (GDPR)</h2>
            <p className="mb-4">
              If you are a resident of the European Economic Area (EEA), you have certain data protection rights. We aim to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.
            </p>
            <p className="mb-4">
              If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
            </p>
            <p className="mb-4">In certain circumstances, you have the following data protection rights:</p>
            <ul className="list-disc pl-6 mb-6 space-y-1">
              <li><strong>The right to access, update or delete the information we have on you.</strong> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</li>
              <li><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
              <li><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</li>
              <li><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</li>
              <li><strong>The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
              <li><strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where we relied on your consent to process your personal information.</li>
            </ul>
            <p className="mb-6">
              Please note that we may ask you to verify your identity before responding to such requests.
            </p>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Service Providers</h2>
            <p className="mb-6">
              We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
            </p>
            <p className="mb-6">
              These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
            </p>

            <h3 className="text-xl font-semibold text-text-primary mb-3">Analytics</h3>
            <p className="mb-4">We may use third-party Service Providers to monitor and analyse the use of our Service.</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li><strong>Google Analytics</strong> - A web analytics service that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.</li>
              <li><strong>Firebase</strong> - An analytics service provided by Google Inc. You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings.</li>
              <li><strong>Mixpanel</strong> - Provided by Mixpanel Inc. You can prevent Mixpanel from using your information for analytics purposes by opting-out.</li>
            </ul>

            <h3 className="text-xl font-semibold text-text-primary mb-3">Behavioral Remarketing</h3>
            <p className="mb-4">We use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li><strong>Google Ads (AdWords)</strong> - A remarketing service provided by Google Inc. You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads by visiting the Google Ads Settings page.</li>
              <li><strong>Facebook</strong> - A remarketing service provided by Facebook Inc. You can learn more about interest-based advertising from Facebook and opt-out from Facebook's interest-based ads.</li>
            </ul>

            <h3 className="text-xl font-semibold text-text-primary mb-3">Payments</h3>
            <p className="mb-4">
              We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).
            </p>
            <p className="mb-4">
              We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
            </p>
            <p className="mb-6">The payment processors we work with include:</p>
            <ul className="list-disc pl-6 mb-6 space-y-1">
              <li>Apple Store In-App Payments</li>
              <li>Google Play In-App Payments</li>
              <li>Stripe</li>
              <li>Razorpay</li>
            </ul>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Refund Policy</h2>
            <p className="mb-6">
              No refunds or credits for partial months or years of service will be refunded to a customer upon cancellation. The amount once paid is non-refundable.
            </p>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Links to Other Sites</h2>
            <p className="mb-4">
              Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
            </p>
            <p className="mb-6">
              We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </p>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Children's Privacy</h2>
            <p className="mb-4">
              Our Service does not address anyone under the age of 18 ("Children").
            </p>
            <p className="mb-4">
              We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
            </p>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Changes to This Privacy Policy</h2>
            <p className="mb-4">
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="mb-6">
              We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.
            </p>
            <p className="mb-6">
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>

            <h2 className="text-2xl font-semibold text-text-primary mb-4">Contact Us</h2>
            <p className="mb-6">
              If you have any questions about this Privacy Policy, please contact us at support@wotzapmsg.com
            </p>
          </div>
          <div className="text-center mt-8">
            <p className="text-sm text-gray-600">For any privacy-related questions, contact us at <a href="mailto:support@wotzapmsg.com" className="text-primary underline">support@wotzapmsg.com</a> or <a href="tel:9316360039" className="text-primary underline">9316360039</a>.</p>
          </div>
        </div>
      </div>
    </div>
  </Layout>
);

export default PrivacyPolicy; 